/**
 * Top Trending & Viral Caption Style Presets Engine
 * Features 100 Curated Unique Presets & 100 Pro Animation Effects
 */

export interface CaptionAnimationEffect {
  id: string;
  name: string;
  icon: string;
  category: 'kinetic' | 'motion' | 'glow' | 'creative';
  description: string;
}

export const ANIMATION_EFFECTS: CaptionAnimationEffect[] = [
  { id: 'none', name: 'Static Clean', icon: '⏹️', category: 'kinetic', description: 'Clean static typography without motion' },
  { id: 'single-word', name: '1-Word Solo Flash (Viral)', icon: '⚡', category: 'kinetic', description: 'Displays ONLY the single spoken word at a time for ultra retention' },
  { id: 'one-word-pop', name: '1-Word Punch Pop', icon: '💥', category: 'kinetic', description: 'Explosive scale punch showing strictly one word at a time' },
  { id: 'typewriter', name: 'Typewriter Letter-by-Letter', icon: '⌨️', category: 'kinetic', description: 'Dynamic typing effect letter by letter with cursor' },
  { id: 'typewriter-word', name: 'Typewriter Word-by-Word', icon: '🔤', category: 'kinetic', description: 'Punchy reveal word by word in sync' },
  { id: 'word-pop', name: 'Kinetic Word Pop', icon: '💥', category: 'kinetic', description: 'Zoom bounce punch on current active word' },
  { id: 'karaoke', name: 'Karaoke Neon Highlight', icon: '🎤', category: 'kinetic', description: 'Singing / talking highlight that sweeps through words' },
  { id: 'wave', name: 'Smooth Wave Float', icon: '🌊', category: 'motion', description: 'Gentle undulating wave float for aesthetic vibes' },
  { id: 'bounce', name: 'Elastic Bouncing Pop', icon: '🎈', category: 'motion', description: 'Springy playful bounce upon entering' },
  { id: 'glitch', name: 'Cyberpunk RGB Glitch', icon: '👾', category: 'creative', description: 'Cybernetic color aberration and twitch' },
  { id: 'fade-up', name: 'Smooth Fade Slide Up', icon: '⬆️', category: 'motion', description: 'Graceful upward slide with opacity fade' },
  { id: 'fade-down', name: 'Drop In Fade Down', icon: '⬇️', category: 'motion', description: 'Smooth downward drop entrance' },
  { id: 'zoom-in', name: 'Dynamic Scale Zoom In', icon: '🔍', category: 'motion', description: 'Punchy scale expansion from center' },
  { id: 'zoom-out', name: 'Cinematic Zoom Out', icon: '🔎', category: 'motion', description: 'Subtle high-end documentary zoom drift' },
  { id: 'pulse-glow', name: 'Neon Pulse Glow', icon: '✨', category: 'glow', description: 'Rhythmic breathing light glow aura' },
  { id: 'flip-x', name: '3D Flip X Rotate', icon: '🔄', category: 'creative', description: 'Horizontal 3D rotation flip' },
  { id: 'flip-y', name: '3D Coin Flip Y', icon: '🔁', category: 'creative', description: 'Vertical 3D spin flip effect' },
  { id: 'rubberband', name: 'Rubberband Stretch', icon: '🎯', category: 'motion', description: 'High-energy squash and elastic rebound' },
  { id: 'shake', name: 'Impact Earthquake Shake', icon: '⚡', category: 'motion', description: 'Vigorous rumble shake for loud punchlines' },
  { id: 'jello', name: 'Jello Wobble', icon: '🍮', category: 'motion', description: 'Gelatin wobble for comedic / fun reels' },
  { id: 'swing', name: 'Pendulum Swing', icon: '🎪', category: 'motion', description: 'Smooth pendulum swinging from top anchor' },
  { id: 'wobble', name: 'Horizontal Sway Wobble', icon: '🪀', category: 'motion', description: 'Rhythmic back-and-forth sway' },
  { id: 'heartbeat', name: 'Heartbeat Throb', icon: '💓', category: 'motion', description: 'Double pulse throb for dramatic beats' },
  { id: 'blur-reveal', name: 'Lens Blur to Sharp', icon: '🌫️', category: 'creative', description: 'Camera focus rack from blur to crystal sharp' },
  { id: 'shimmer', name: 'Metallic Light Shimmer', icon: '💫', category: 'glow', description: 'Shiny reflective light sweep across letters' },
  { id: 'slide-left', name: 'Speed Swipe Left', icon: '⬅️', category: 'motion', description: 'High-velocity slide entrance from right to left' },
  { id: 'slide-right', name: 'Speed Swipe Right', icon: '➡️', category: 'motion', description: 'High-velocity slide entrance from left to right' },
  { id: 'strobe', name: 'Strobe Flash Impact', icon: '🚨', category: 'glow', description: 'Rapid flash strobe impact for high BPM drops' },
  { id: 'color-cycle', name: 'Rainbow Hue Cycle', icon: '🌈', category: 'glow', description: 'Continuous cycling through spectrum colors' },
  { id: 'split-drop', name: 'Letter Drop Bounce', icon: '💥', category: 'kinetic', description: 'Letters cascade and drop with weight' },
  { id: 'vhs-flicker', name: '90s VHS Camcorder Static', icon: '📼', category: 'creative', description: 'Retro analog tape tracking & grain flicker' },
  { id: 'fire-flame', name: 'Fiery Blaze Flicker', icon: '🔥', category: 'glow', description: 'Fiery flame flicker with ember warmth' },
  { id: 'ice-freeze', name: 'Frost Shiver Freeze', icon: '❄️', category: 'glow', description: 'Chilled frosted crystallize glow' },
  { id: 'rotate-in', name: 'Spiral Whirlwind Rotate', icon: '🌀', category: 'creative', description: 'Spinning spiral vortex reveal' },
  { id: 'float-slow', name: 'Gentle Cloud Float', icon: '☁️', category: 'motion', description: 'Ultra peaceful slow drifting movement' },
  { id: 'cinematic-drift', name: 'Cinematic Pan Drift', icon: '🎬', category: 'motion', description: 'Slow dramatic Hollywood movie pan' },
  { id: 'pop-out', name: 'Explosive Pop Out', icon: '💣', category: 'kinetic', description: 'Explosive scale expansion punch' },
  { id: 'neon-flicker', name: 'Neon Sign Short Circuit', icon: '💡', category: 'glow', description: 'Cyber neon bulb blinking effect' },
  { id: 'heartbeat-pulse', name: 'Double Heart Pulse', icon: '🫀', category: 'motion', description: 'Double thump heart thump rhythm' },
  { id: 'breathing-scale', name: 'Deep Breathing Scale', icon: '🫁', category: 'motion', description: 'Subtle rhythmic breathing expansion' },
  { id: 'speed-warp', name: 'Hyperspace Speed Warp', icon: '🚀', category: 'kinetic', description: 'Warp speed zoom entrance' },
  { id: 'spotlight-glow', name: 'Stage Spotlight Aura', icon: '🔦', category: 'glow', description: 'Circular stage spotlight illumination' },
  { id: 'laser-sweep', name: 'Laser Beam Sweep', icon: '🔴', category: 'glow', description: 'Horizontal laser beam wipe' },
  { id: 'sparkle-flash', name: 'Golden Sparkle Star', icon: '⭐', category: 'glow', description: 'Twinkling gold starburst flashes' },
  { id: 'slam-down', name: 'Heavy Anvil Slam', icon: '🔨', category: 'kinetic', description: 'High gravity downward slam impact' },
  { id: 'float-up', name: 'Zero-G Helium Lift', icon: '🎈', category: 'motion', description: 'Weightless floating ascension' },
  { id: 'tilt-rock', name: 'Subtle Tilt Rocking', icon: '📐', category: 'motion', description: 'Gentle rhythmic tilt rocking' },
  { id: 'horizon-pan', name: 'Sunset Horizon Pan', icon: '🌅', category: 'motion', description: 'Smooth sideways cinematic glide' },
  { id: 'magnetic-snap', name: 'Magnetic Force Snap', icon: '🧲', category: 'kinetic', description: 'High-speed magnetic snapping' },
  { id: 'flashbang', name: 'Flashbang White Flash', icon: '💥', category: 'glow', description: 'Intense whiteout strobe flash' },
  { id: 'tv-static', name: 'CRT Monitor Glitch', icon: '📺', category: 'creative', description: 'Vintage TV cathode ray flicker' },
  { id: 'diamond-shimmer', name: 'Diamond Crystal Shimmer', icon: '💎', category: 'glow', description: 'Prismatic crystal diamond sparkle' },
  { id: 'electric-shock', name: 'High Voltage Shock', icon: '⚡', category: 'glow', description: 'Electrical lightning buzz' },
  { id: 'spring-pop', name: 'Spring Pop Elastic', icon: '🌀', category: 'motion', description: 'Ultra elastic coil spring bounce' },
  { id: 'roll-in', name: '3D Cylinder Roll In', icon: '🛹', category: 'creative', description: 'Barrel roll entrance from top' },
  { id: 'supernova-flare', name: 'Supernova Solar Flare', icon: '☀️', category: 'glow', description: 'Blinding cosmic burst of light' },
  { id: 'matrix-drop', name: 'Matrix Cyber Code Drop', icon: '💻', category: 'kinetic', description: 'Digital code rain stream entrance' },
  { id: 'ghost-slide', name: 'Phantom Ghost Slide', icon: '👻', category: 'creative', description: 'Ethereal blurred ghosting trail' },
  { id: 'liquid-ripple', name: 'Liquid Ripple Splash', icon: '💧', category: 'motion', description: 'Fluid water ripple distortion' },
  { id: 'snap-bounce', name: 'Snap Finger Bounce', icon: '🫰', category: 'kinetic', description: 'Crisp rhythmic snap pop' },
  { id: 'tumble-spin', name: '3D Tumble Spin Roll', icon: '🤸', category: 'creative', description: 'Full 360 degree tumble spin' },
  { id: 'hologram-flicker', name: 'Sci-Fi Hologram Flicker', icon: '📡', category: 'creative', description: 'Translucent blue hologram twitch' },
  { id: 'feather-fade', name: 'Soft Feather Fade', icon: '🪶', category: 'motion', description: 'Ultra soft velvet fade transition' },
  { id: 'flashlight-reveal', name: 'Night Flashlight Sweep', icon: '🔦', category: 'glow', description: 'Searchlight reveal effect' },
  { id: 'stretch-x', name: 'Horizontal Elastic Stretch', icon: '↔️', category: 'motion', description: 'Wide horizontal morph expansion' },
  { id: 'stretch-y', name: 'Vertical Elastic Stretch', icon: '↕️', category: 'motion', description: 'Tall vertical morph expansion' },
  { id: 'thunder-strike', name: 'Thunder Strike Impact', icon: '🌩️', category: 'glow', description: 'Lightning flash with micro shake' },
  { id: 'nebula-drift', name: 'Deep Space Nebula Drift', icon: '🌌', category: 'motion', description: 'Galactic slow cosmic drift' },
  { id: 'grid-ping', name: 'Sonar Grid Radar Ping', icon: '🛰️', category: 'kinetic', description: 'Submarine radar sonar sweep' },
  { id: 'bubble-float', name: 'Soap Bubble Pop Float', icon: '🫧', category: 'motion', description: 'Floating bubble popping into text' },
  { id: 'twirl-snap', name: 'Pirouette Twirl Snap', icon: '💫', category: 'creative', description: 'Fast spin into lock position' },
  { id: 'bass-rumble', name: 'Sub-Bass Woofer Rumble', icon: '🔊', category: 'motion', description: 'Low frequency heavy bass vibration' },
  { id: 'soft-glow', name: 'Moonlight Soft Glow', icon: '🌙', category: 'glow', description: 'Peaceful celestial moonlight aura' },
  { id: 'arcade-blink', name: '8-Bit Arcade 1UP Blink', icon: '🕹️', category: 'creative', description: 'Retro 8-bit game start blink' },
  { id: 'voltage-sparks', name: 'Arc Welding Voltage Sparks', icon: '⚡', category: 'glow', description: 'Bright electrical sparks emitting' },
  { id: 'wind-swirl', name: 'Autumn Wind Swirl', icon: '🍃', category: 'motion', description: 'Swirling breeze motion path' },
  { id: 'comic-zoom', name: 'Marvel Comic Panel Zoom', icon: '🗯️', category: 'kinetic', description: 'Action comic superhero dynamic zoom' },
  { id: 'magnetic-hover', name: 'Maglev Magnetic Hover', icon: '🚝', category: 'motion', description: 'Frictionless magnetic levitation' },
  { id: 'card-twist', name: 'Poker Card Flip Twist', icon: '🃏', category: 'creative', description: 'Sleight-of-hand card flip twist' },
  { id: 'solar-pulse', name: 'Sunburst Solar Pulse', icon: '🌞', category: 'glow', description: 'Radiating thermal heatwave pulse' },
  { id: 'prism-reflect', name: 'Prism Glass Dispersion', icon: '🔮', category: 'glow', description: 'Rainbow prism glass reflection' },
  { id: 'letterbox-drift', name: 'Anamorphic Lens Drift', icon: '🎞️', category: 'motion', description: 'Cinemascope anamorphic lens glide' },
  { id: 'stamp-impact', name: 'Passport Rubber Stamp', icon: '📮', category: 'kinetic', description: 'Solid heavy ink stamp press' },
  { id: 'skew-slide', name: 'Speed Racer Skew Slide', icon: '🏎️', category: 'motion', description: 'Fast italicized slant slide' },
  { id: 'vaporwave-pulse', name: 'Vaporwave Neon Haze', icon: '🌴', category: 'glow', description: 'Miami sunset dreamy haze' },
  { id: 'morse-flicker', name: 'Telegraph Morse Strobe', icon: '📻', category: 'creative', description: 'Rhythmic morse code blink pulse' },
  { id: 'liquid-morph', name: 'Molten Gold Morph', icon: '🧪', category: 'motion', description: 'Organic fluid liquid transformation' },
  { id: 'swing-left', name: 'Left Pivot Door Swing', icon: '🚪', category: 'creative', description: '3D hinge swing from left edge' },
  { id: 'swing-right', name: 'Right Pivot Door Swing', icon: '🚪', category: 'creative', description: '3D hinge swing from right edge' },
  { id: 'outline-pulse', name: 'Neon Wireframe Pulse', icon: '🔳', category: 'glow', description: 'Glowing wireframe stroke breathe' },
  { id: 'particle-flutter', name: 'Stardust Particle Flutter', icon: '✨', category: 'glow', description: 'Floating glitter dust sparkle' },
  { id: 'film-shake', name: '16mm Projector Gate Weave', icon: '📽️', category: 'creative', description: 'Vintage celluloid reel jitter' },
  { id: 'hyper-drive', name: 'Millennium Hyper Drive', icon: '🌠', category: 'kinetic', description: 'Starfield streak velocity blur' },
  { id: 'aurora-glow', name: 'Northern Lights Aurora', icon: '🌌', category: 'glow', description: 'Emerald violet celestial curtain' },
  { id: 'quick-orbit', name: 'Orbital Satellite Spin', icon: '🛰️', category: 'motion', description: 'Quick smooth circular orbit' },
  { id: 'echo-bounce', name: 'Echo Sonar Ripple Bounce', icon: '📡', category: 'kinetic', description: 'Repeating rebound impact' },
  { id: 'velvet-drift', name: 'Silk Velvet Smooth Pan', icon: '🎀', category: 'motion', description: 'Buttery smooth 60fps pan' },
  { id: 'laser-strobe', name: 'EDM Festival Laser Strobe', icon: '🪩', category: 'glow', description: 'High tempo dance strobe hits' },
  { id: 'sunrise-flare', name: 'Golden Hour Sunset Flare', icon: '🌇', category: 'glow', description: 'Warm amber sun flare beam' },
  { id: 'noir-shadow', name: 'Detective Noir Shutter', icon: '🕵️', category: 'creative', description: 'Venetian blind shadow reveal' },
  { id: 'word-warp', name: 'Warp Speed Kinetic Text', icon: '🌌', category: 'kinetic', description: 'Dynamic elastic word warp impact' },
  { id: 'viral-ultimate', name: 'Viral Ultimate Retention Pop', icon: '👑', category: 'kinetic', description: 'Maximum attention retention pop animation' },
];

export interface CaptionPreset {
  id: string;
  name: string;
  category: 'viral' | 'animation' | 'aesthetic' | 'cinematic' | 'hindi';
  fontFamily: string;
  color: string;
  boxStyle: 'glass' | 'box' | 'clean' | 'neon' | 'pill' | 'outline' | 'gradient';
  boxBgColor?: string;
  opacity: number;
  animationType: string;
  textShadow?: string;
  textTransform?: 'uppercase' | 'none';
  badge?: string;
  description?: string;
}

export const CAPTION_PRESETS: CaptionPreset[] = [
  // 1-15: VIRAL SHORTS & REELS SUPERSTARS
  { id: 'hormozi-1word-solo', name: 'Hormozi 1-Word Flash (Solo)', category: 'viral', fontFamily: 'Anton', color: '#4ade80', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.95)', opacity: 1, animationType: 'single-word', textTransform: 'uppercase' },
  { id: 'tiktok-1word-pop', name: 'TikTok 1-Word Punch Pop', category: 'viral', fontFamily: 'Montserrat', color: '#fde047', boxStyle: 'pill', boxBgColor: 'rgba(15, 23, 42, 0.9)', opacity: 1, animationType: 'one-word-pop', textTransform: 'uppercase' },
  { id: 'mrbeast-punch', name: 'MrBeast Bold Punch', category: 'viral', fontFamily: 'Anton', color: '#fde047', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.9)', opacity: 1, animationType: 'word-pop', textTransform: 'uppercase' },
  { id: 'hormozi-kinetic', name: 'Alex Hormozi Lime', category: 'viral', fontFamily: 'Bebas Neue', color: '#4ade80', boxStyle: 'clean', opacity: 1, animationType: 'karaoke', textTransform: 'uppercase' },
  { id: 'ali-abdaal-clean', name: 'Ali Abdaal Clean Pill', category: 'viral', fontFamily: 'Poppins', color: '#ffffff', boxStyle: 'pill', boxBgColor: 'rgba(15, 23, 42, 0.85)', opacity: 0.95, animationType: 'fade-up' },
  { id: 'iman-gadzhi-gold', name: 'Iman Gadzhi Luxury', category: 'viral', fontFamily: 'Playfair Display', color: '#fef08a', boxStyle: 'glass', boxBgColor: 'rgba(10, 10, 20, 0.8)', opacity: 1, animationType: 'shimmer' },
  { id: 'garyvee-impact', name: 'GaryVee Heavy Impact', category: 'viral', fontFamily: 'Archivo Black', color: '#ffffff', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'zoom-in', textTransform: 'uppercase' },
  { id: 'joe-rogan-pod', name: 'Joe Rogan Condensed', category: 'viral', fontFamily: 'Oswald', color: '#fde047', boxStyle: 'clean', opacity: 1, animationType: 'rubberband', textTransform: 'uppercase' },
  { id: 'dan-koe-focus', name: 'Dan Koe Minimal Modern', category: 'viral', fontFamily: 'Inter', color: '#ffffff', boxStyle: 'clean', opacity: 1, animationType: 'fade-up' },
  { id: 'andrew-huberman', name: 'Huberman Lab Science', category: 'viral', fontFamily: 'Montserrat', color: '#38bdf8', boxStyle: 'pill', boxBgColor: 'rgba(2, 6, 23, 0.9)', opacity: 1, animationType: 'typewriter-word' },
  { id: 'david-goggins', name: 'Goggins Unstoppable', category: 'viral', fontFamily: 'Impact', color: '#ef4444', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'shake', textTransform: 'uppercase' },
  { id: 'logan-paul-prime', name: 'Prime Energy Punch', category: 'viral', fontFamily: 'Anton', color: '#a855f7', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.88)', opacity: 1, animationType: 'bounce', textTransform: 'uppercase' },
  { id: 'sam-sulek-raw', name: 'Sam Sulek Raw Heavy', category: 'viral', fontFamily: 'Teko', color: '#ffffff', boxStyle: 'box', boxBgColor: 'rgba(30, 41, 59, 0.95)', opacity: 1, animationType: 'slam-down', textTransform: 'uppercase' },
  { id: 'lex-fridman-ai', name: 'Lex Fridman Deep Mind', category: 'viral', fontFamily: 'Space Grotesk', color: '#e2e8f0', boxStyle: 'glass', boxBgColor: 'rgba(15, 23, 42, 0.8)', opacity: 0.95, animationType: 'blur-reveal' },
  { id: 'news-breaking-red', name: 'Breaking News Urgency', category: 'viral', fontFamily: 'Oswald', color: '#ffffff', boxStyle: 'box', boxBgColor: '#dc2626', opacity: 1, animationType: 'strobe', textTransform: 'uppercase' },
  { id: 'white-sticker-pop', name: 'White Sticker Badge', category: 'viral', fontFamily: 'Montserrat', color: '#090d16', boxStyle: 'box', boxBgColor: '#ffffff', opacity: 1, animationType: 'bounce', textTransform: 'uppercase' },
  { id: 'viral-yellow-banner', name: 'Caution High Retention', category: 'viral', fontFamily: 'Anton', color: '#000000', boxStyle: 'box', boxBgColor: '#facc15', opacity: 1, animationType: 'word-pop', textTransform: 'uppercase' },

  // 16-30: ROYAL HINDI & BOLLYWOOD LEGENDS
  { id: 'hindi-royal-saffron', name: 'Devanagari Saffron Gold', category: 'hindi', fontFamily: 'Rozha One', color: '#fbbf24', boxStyle: 'glass', boxBgColor: 'rgba(69, 10, 10, 0.85)', opacity: 1, animationType: 'shimmer' },
  { id: 'desi-swag-neon', name: 'Desi Swag Street', category: 'hindi', fontFamily: 'Yatra One', color: '#38bdf8', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.9)', opacity: 1, animationType: 'glitch' },
  { id: 'bollywood-retro-70s', name: 'Bollywood 70s Romance', category: 'hindi', fontFamily: 'Rozha One', color: '#f43f5e', boxStyle: 'glass', boxBgColor: 'rgba(30, 10, 40, 0.75)', opacity: 0.95, animationType: 'wave' },
  { id: 'royal-maratha-gold', name: 'Maratha Royal Dynasty', category: 'hindi', fontFamily: 'Yatra One', color: '#f59e0b', boxStyle: 'box', boxBgColor: 'rgba(20, 10, 0, 0.92)', opacity: 1, animationType: 'fire-flame' },
  { id: 'sufi-mystique-white', name: 'Sufi Mystique Serene', category: 'hindi', fontFamily: 'Kalam', color: '#ffffff', boxStyle: 'clean', opacity: 1, animationType: 'float-slow' },
  { id: 'punjabi-beats-neon', name: 'Punjabi Dhol Beats', category: 'hindi', fontFamily: 'Modak', color: '#22c55e', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'bounce' },
  { id: 'vedic-golden-dawn', name: 'Vedic Golden Dawn', category: 'hindi', fontFamily: 'Rozha One', color: '#fde68a', boxStyle: 'glass', boxBgColor: 'rgba(40, 20, 5, 0.8)', opacity: 1, animationType: 'sparkle-flash' },
  { id: 'jaipur-ruby-palace', name: 'Jaipur Ruby Palace', category: 'hindi', fontFamily: 'Yatra One', color: '#fda4af', boxStyle: 'pill', boxBgColor: 'rgba(136, 19, 55, 0.9)', opacity: 1, animationType: 'pulse-glow' },
  { id: 'ganga-ghat-peace', name: 'Ganga Ghat Serenade', category: 'hindi', fontFamily: 'Kalam', color: '#e0f2fe', boxStyle: 'clean', opacity: 0.95, animationType: 'float-slow' },
  { id: 'taj-ivory-elegance', name: 'Taj Mahal Pure Ivory', category: 'hindi', fontFamily: 'Rozha One', color: '#ffffff', boxStyle: 'clean', opacity: 1, animationType: 'fade-up' },
  { id: 'kashi-darshan-gold', name: 'Kashi Darshan Aura', category: 'hindi', fontFamily: 'Yatra One', color: '#f59e0b', boxStyle: 'pill', boxBgColor: 'rgba(40, 15, 0, 0.85)', opacity: 1, animationType: 'sunrise-flare' },
  { id: 'sholay-action-punch', name: 'Sholay Action Punch', category: 'hindi', fontFamily: 'Modak', color: '#ef4444', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'shake' },
  { id: 'shayari-gazal-mood', name: 'Urdu Shayari Ghazal', category: 'hindi', fontFamily: 'Kalam', color: '#fbcfe8', boxStyle: 'glass', boxBgColor: 'rgba(15, 23, 42, 0.8)', opacity: 0.95, animationType: 'blur-reveal' },
  { id: 'mumbai-local-rush', name: 'Mumbai Fast Local', category: 'hindi', fontFamily: 'Teko', color: '#facc15', boxStyle: 'box', boxBgColor: 'rgba(2, 6, 23, 0.95)', opacity: 1, animationType: 'speed-warp', textTransform: 'uppercase' },
  { id: 'hindustani-classical', name: 'Raga Classical Melody', category: 'hindi', fontFamily: 'Rozha One', color: '#d8b4fe', boxStyle: 'clean', opacity: 1, animationType: 'wave' },

  // 31-45: CYBERPUNK, SYNTHWAVE & NEON GLOW
  { id: 'cyber-matrix-green', name: 'Matrix Terminal Green', category: 'animation', fontFamily: 'Share Tech Mono', color: '#22c55e', boxStyle: 'box', boxBgColor: 'rgba(0, 20, 5, 0.95)', opacity: 1, animationType: 'matrix-drop' },
  { id: 'tokyo-neon-drift', name: 'Tokyo Neon Night Drift', category: 'animation', fontFamily: 'Orbitron', color: '#ec4899', boxStyle: 'glass', boxBgColor: 'rgba(10, 0, 25, 0.85)', opacity: 1, animationType: 'glitch' },
  { id: 'synthwave-80s-sunset', name: 'Synthwave 80s Sunset', category: 'animation', fontFamily: 'Audiowide', color: '#38bdf8', boxStyle: 'box', boxBgColor: '#3b0764', opacity: 0.95, animationType: 'color-cycle' },
  { id: 'cyberpunk-2077-yellow', name: 'Night City 2077 Yellow', category: 'animation', fontFamily: 'Orbitron', color: '#000000', boxStyle: 'box', boxBgColor: '#fcee09', opacity: 1, animationType: 'glitch', textTransform: 'uppercase' },
  { id: 'acid-lime-rave', name: 'Acid Lime Rave Laser', category: 'animation', fontFamily: 'Teko', color: '#84cc16', boxStyle: 'clean', opacity: 1, animationType: 'laser-strobe', textTransform: 'uppercase' },
  { id: 'tron-cyan-grid', name: 'Tron Cyber Legacy Cyan', category: 'animation', fontFamily: 'Audiowide', color: '#06b6d4', boxStyle: 'outline', opacity: 1, animationType: 'pulse-glow' },
  { id: 'vaporwave-aesthetic', name: 'Vaporwave Sunset Horizon', category: 'animation', fontFamily: 'Space Grotesk', color: '#f472b6', boxStyle: 'gradient', opacity: 0.9, animationType: 'vaporwave-pulse' },
  { id: 'laser-beam-violet', name: 'Deep Violet Laser Beam', category: 'animation', fontFamily: 'Orbitron', color: '#c084fc', boxStyle: 'box', boxBgColor: 'rgba(30, 10, 60, 0.9)', opacity: 1, animationType: 'laser-sweep' },
  { id: 'dark-web-hacker', name: 'Dark Web Hacker Prompt', category: 'animation', fontFamily: 'Fira Code', color: '#10b981', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'typewriter' },
  { id: 'blade-runner-amber', name: 'Blade Runner 2049 Amber', category: 'animation', fontFamily: 'Oswald', color: '#f97316', boxStyle: 'glass', boxBgColor: 'rgba(20, 10, 0, 0.85)', opacity: 1, animationType: 'dust-drift' },
  { id: 'arcade-1up-pixel', name: 'Arcade 8-Bit Retro 1UP', category: 'animation', fontFamily: 'Press Start 2P', color: '#facc15', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'arcade-blink' },
  { id: 'neon-plasma-pink', name: 'Neon Plasma High Beam', category: 'animation', fontFamily: 'Montserrat', color: '#ff2d55', boxStyle: 'pill', boxBgColor: 'rgba(0, 0, 0, 0.88)', opacity: 1, animationType: 'neon-flicker' },
  { id: 'quantum-flux-blue', name: 'Quantum Electric Flux', category: 'animation', fontFamily: 'Space Grotesk', color: '#60a5fa', boxStyle: 'glass', boxBgColor: 'rgba(15, 23, 42, 0.85)', opacity: 1, animationType: 'electric-shock' },
  { id: 'holographic-ai-hud', name: 'Iron Man AI HUD Cyan', category: 'animation', fontFamily: 'Share Tech Mono', color: '#22d3ee', boxStyle: 'clean', opacity: 0.9, animationType: 'hologram-flicker' },
  { id: 'super-strobe-edm', name: 'Tomorrowland Strobe EDM', category: 'animation', fontFamily: 'Impact', color: '#ffffff', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'strobe', textTransform: 'uppercase' },

  // 46-60: CINEMATIC, NETFLIX & HOLLYWOOD
  { id: 'netflix-red-title', name: 'Netflix Original Red', category: 'cinematic', fontFamily: 'Bebas Neue', color: '#e50914', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.92)', opacity: 1, animationType: 'zoom-in', textTransform: 'uppercase' },
  { id: 'imax-blockbuster', name: 'IMAX 70mm Blockbuster', category: 'cinematic', fontFamily: 'Cinzel', color: '#f8fafc', boxStyle: 'clean', opacity: 1, animationType: 'cinematic-drift', textTransform: 'uppercase' },
  { id: 'documentary-parchment', name: 'BBC History Parchment', category: 'cinematic', fontFamily: 'Playfair Display', color: '#fef3c7', boxStyle: 'glass', boxBgColor: 'rgba(20, 15, 10, 0.85)', opacity: 0.95, animationType: 'fade-up' },
  { id: 'warner-bros-gold', name: 'Hollywood Classic Gold', category: 'cinematic', fontFamily: 'Cinzel', color: '#fbbf24', boxStyle: 'clean', opacity: 1, animationType: 'shimmer' },
  { id: 'true-crime-charcoal', name: 'True Crime Mystery Noir', category: 'cinematic', fontFamily: 'Oswald', color: '#e2e8f0', boxStyle: 'box', boxBgColor: '#18181b', opacity: 0.95, animationType: 'noir-shadow', textTransform: 'uppercase' },
  { id: 'natgeo-yellow-box', name: 'National Geographic Yellow', category: 'cinematic', fontFamily: 'Montserrat', color: '#ffffff', boxStyle: 'box', boxBgColor: '#eab308', opacity: 1, animationType: 'fade-down' },
  { id: 'bbc-horizon-clean', name: 'BBC Horizon Science Clean', category: 'cinematic', fontFamily: 'Inter', color: '#ffffff', boxStyle: 'pill', boxBgColor: 'rgba(0, 0, 0, 0.75)', opacity: 0.9, animationType: 'fade-up' },
  { id: 'vhs-retro-camcorder', name: 'VHS 1994 Home Camcorder', category: 'cinematic', fontFamily: 'Share Tech Mono', color: '#facc15', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.7)', opacity: 1, animationType: 'vhs-flicker' },
  { id: 'vintage-film-noir', name: '1940s Classic Film Noir', category: 'cinematic', fontFamily: 'Playfair Display', color: '#ffffff', boxStyle: 'clean', opacity: 1, animationType: 'film-shake' },
  { id: 'marvel-comic-action', name: 'Marvel Universe Action', category: 'cinematic', fontFamily: 'Bangers', color: '#fde047', boxStyle: 'box', boxBgColor: '#dc2626', opacity: 1, animationType: 'comic-zoom' },
  { id: 'hbo-drama-subtitles', name: 'HBO Dramatic Masterpiece', category: 'cinematic', fontFamily: 'Inter', color: '#ffea79', boxStyle: 'clean', opacity: 1, animationType: 'fade-up' },
  { id: 'space-odyssey-minimal', name: '2001 Space Monolith', category: 'cinematic', fontFamily: 'Space Grotesk', color: '#ffffff', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'float-slow', textTransform: 'uppercase' },
  { id: 'interstellar-drift', name: 'Interstellar Cosmic Pan', category: 'cinematic', fontFamily: 'Cinzel', color: '#bae6fd', boxStyle: 'clean', opacity: 1, animationType: 'nebula-drift' },
  { id: 'pulp-fiction-yellow', name: 'Tarantino Retro Yellow', category: 'cinematic', fontFamily: 'Impact', color: '#facc15', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'rubberband', textTransform: 'uppercase' },
  { id: 'anime-sub-yellow', name: 'Japanese Anime Yellow Sub', category: 'cinematic', fontFamily: 'Poppins', color: '#fef08a', boxStyle: 'clean', opacity: 1, animationType: 'typewriter-word' },

  // 61-75: MODERN AESTHETIC, MINIMALIST & EDITORIAL
  { id: 'vogue-luxury-editorial', name: 'Vogue Haute Couture', category: 'aesthetic', fontFamily: 'Playfair Display', color: '#ffffff', boxStyle: 'clean', opacity: 1, animationType: 'velvet-drift' },
  { id: 'scandinavian-soft-zen', name: 'Scandinavian Minimal Zen', category: 'aesthetic', fontFamily: 'Inter', color: '#f1f5f9', boxStyle: 'pill', boxBgColor: 'rgba(30, 41, 59, 0.7)', opacity: 0.9, animationType: 'feather-fade' },
  { id: 'coffee-mocha-warm', name: 'Warm Roast Coffee Mocha', category: 'aesthetic', fontFamily: 'Kalam', color: '#fed7aa', boxStyle: 'pill', boxBgColor: 'rgba(41, 24, 16, 0.88)', opacity: 0.95, animationType: 'float-slow' },
  { id: 'matcha-latte-calm', name: 'Matcha Green Latte Calm', category: 'aesthetic', fontFamily: 'Poppins', color: '#dcfce7', boxStyle: 'pill', boxBgColor: 'rgba(20, 83, 45, 0.85)', opacity: 0.9, animationType: 'wave' },
  { id: 'pastel-pink-blush', name: 'Sweet Pastel Blush Pink', category: 'aesthetic', fontFamily: 'Pacifico', color: '#f43f5e', boxStyle: 'pill', boxBgColor: 'rgba(253, 242, 248, 0.92)', opacity: 0.95, animationType: 'bubble-float' },
  { id: 'midnight-moody-blue', name: 'Midnight Deep Moody Blue', category: 'aesthetic', fontFamily: 'Montserrat', color: '#93c5fd', boxStyle: 'glass', boxBgColor: 'rgba(15, 23, 42, 0.9)', opacity: 0.95, animationType: 'soft-glow' },
  { id: 'apple-san-francisco', name: 'Apple Cupertino Keynote', category: 'aesthetic', fontFamily: 'Inter', color: '#ffffff', boxStyle: 'glass', boxBgColor: 'rgba(0, 0, 0, 0.65)', opacity: 1, animationType: 'fade-up' },
  { id: 'luxury-silk-pearl', name: 'Silk Pearl Champagne', category: 'aesthetic', fontFamily: 'Playfair Display', color: '#fef3c7', boxStyle: 'clean', opacity: 1, animationType: 'diamond-shimmer' },
  { id: 'brutalist-raw-black', name: 'Raw Brutalist Mono Grid', category: 'aesthetic', fontFamily: 'Space Grotesk', color: '#ffffff', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'magnetic-snap', textTransform: 'uppercase' },
  { id: 'obsidian-stealth-dark', name: 'Obsidian Stealth Matte', category: 'aesthetic', fontFamily: 'Montserrat', color: '#94a3b8', boxStyle: 'box', boxBgColor: '#090d16', opacity: 1, animationType: 'blur-reveal' },
  { id: 'sunset-cloud-drift', name: 'Golden Sunset Cloud Drift', category: 'aesthetic', fontFamily: 'Kalam', color: '#ffedd5', boxStyle: 'clean', opacity: 0.95, animationType: 'sunrise-flare' },
  { id: 'frosted-ice-crystal', name: 'Frosted Crystalline Glass', category: 'aesthetic', fontFamily: 'Inter', color: '#f8fafc', boxStyle: 'glass', boxBgColor: 'rgba(255, 255, 255, 0.15)', opacity: 0.9, animationType: 'ice-freeze' },
  { id: 'lavender-dream-serene', name: 'Lavender Twilight Serene', category: 'aesthetic', fontFamily: 'Poppins', color: '#f3e8ff', boxStyle: 'pill', boxBgColor: 'rgba(88, 28, 135, 0.8)', opacity: 0.95, animationType: 'wave' },
  { id: 'emerald-mint-glow', name: 'Emerald Mint Clean Breath', category: 'aesthetic', fontFamily: 'Montserrat', color: '#a7f3d0', boxStyle: 'pill', boxBgColor: 'rgba(6, 78, 59, 0.85)', opacity: 0.9, animationType: 'breathing-scale' },
  { id: 'comic-bubble-pop', name: 'Comic Hero Speech Bubble', category: 'aesthetic', fontFamily: 'Bangers', color: '#ffffff', boxStyle: 'box', boxBgColor: '#f59e0b', opacity: 1, animationType: 'bounce' },

  // 76-90: ESPORTS, GAMING & HIGH ENERGY
  { id: 'valorant-radiant-gold', name: 'Valorant Radiant Gold', category: 'viral', fontFamily: 'Teko', color: '#fef08a', boxStyle: 'box', boxBgColor: 'rgba(15, 23, 42, 0.95)', opacity: 1, animationType: 'sparkle-flash', textTransform: 'uppercase' },
  { id: 'apex-legends-amber', name: 'Apex Champion Predator', category: 'viral', fontFamily: 'Oswald', color: '#ea580c', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'slam-down', textTransform: 'uppercase' },
  { id: 'cyber-samurai-katana', name: 'Cyber Samurai Katana Slice', category: 'animation', fontFamily: 'Yatra One', color: '#ef4444', boxStyle: 'clean', opacity: 1, animationType: 'laser-sweep' },
  { id: 'twitch-streamer-purp', name: 'Twitch Partner Purple', category: 'viral', fontFamily: 'Montserrat', color: '#ffffff', boxStyle: 'pill', boxBgColor: '#9146ff', opacity: 1, animationType: 'word-pop' },
  { id: 'cs-tactical-strike', name: 'CS Tactical Bomb Defuse', category: 'viral', fontFamily: 'Share Tech Mono', color: '#e2e8f0', boxStyle: 'box', boxBgColor: 'rgba(20, 30, 20, 0.95)', opacity: 1, animationType: 'typewriter' },
  { id: 'shonen-anime-flame', name: 'Super Saiyan Flame Rage', category: 'animation', fontFamily: 'Bangers', color: '#fde047', boxStyle: 'clean', opacity: 1, animationType: 'fire-flame' },
  { id: 'mecha-titanium-armor', name: 'Titan Mech Heavy Armor', category: 'cinematic', fontFamily: 'Orbitron', color: '#38bdf8', boxStyle: 'box', boxBgColor: 'rgba(15, 23, 42, 0.95)', opacity: 1, animationType: 'heavy-impact' },
  { id: 'speedrun-world-record', name: 'Speedrun WR Sub-10:00', category: 'viral', fontFamily: 'Share Tech Mono', color: '#4ade80', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'hyper-drive' },
  { id: 'dark-souls-victory', name: 'You Defeated Golden Crest', category: 'cinematic', fontFamily: 'Cinzel', color: '#fef08a', boxStyle: 'clean', opacity: 1, animationType: 'shimmer', textTransform: 'uppercase' },
  { id: 'neon-arcade-combo', name: '999x Ultra Combo Street', category: 'animation', fontFamily: 'Press Start 2P', color: '#f43f5e', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'bounce' },
  { id: 'gta-wasted-impact', name: 'GTA Vice City Neon Strip', category: 'viral', fontFamily: 'Pricedown, Impact', color: '#f472b6', boxStyle: 'box', boxBgColor: 'rgba(0, 0, 0, 0.85)', opacity: 1, animationType: 'shake' },
  { id: 'pokemon-crit-hit', name: 'Super Effective Critical', category: 'aesthetic', fontFamily: 'Poppins', color: '#facc15', boxStyle: 'pill', boxBgColor: 'rgba(220, 38, 38, 0.95)', opacity: 1, animationType: 'bounce' },
  { id: 'red-bull-extreme', name: 'Red Bull Nitro Extreme', category: 'viral', fontFamily: 'Teko', color: '#38bdf8', boxStyle: 'box', boxBgColor: '#001a4d', opacity: 1, animationType: 'speed-warp', textTransform: 'uppercase' },
  { id: 'monster-energy-claw', name: 'Monster Green Beast Claw', category: 'viral', fontFamily: 'Impact', color: '#84cc16', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'word-pop' },
  { id: 'subway-surfers-coin', name: 'Subway Surfer Golden Coin', category: 'viral', fontFamily: 'Bangers', color: '#ffffff', boxStyle: 'pill', boxBgColor: '#f59e0b', opacity: 1, animationType: 'spring-pop' },

  // 91-100: DYNAMIC GRADIENT, GLASS & ULTRA VIRAL RETENTION
  { id: 'hyper-gradient-violet', name: 'Hyper Violet Sunset Glow', category: 'viral', fontFamily: 'Montserrat', color: '#ffffff', boxStyle: 'gradient', opacity: 0.95, animationType: 'color-cycle' },
  { id: 'emerald-isle-luxury', name: 'Emerald Forest Glass Pill', category: 'aesthetic', fontFamily: 'Poppins', color: '#f0fdf4', boxStyle: 'pill', boxBgColor: 'rgba(5, 46, 22, 0.9)', opacity: 0.92, animationType: 'aurora-glow' },
  { id: 'cosmic-galaxy-deep', name: 'Cosmic Galaxy Starlight', category: 'animation', fontFamily: 'Space Grotesk', color: '#c084fc', boxStyle: 'glass', boxBgColor: 'rgba(20, 5, 40, 0.85)', opacity: 1, animationType: 'particle-flutter' },
  { id: 'coral-reef-vibrant', name: 'Vibrant Coral Reef Warm', category: 'aesthetic', fontFamily: 'Montserrat', color: '#ffffff', boxStyle: 'pill', boxBgColor: '#fb7185', opacity: 1, animationType: 'bounce' },
  { id: 'deep-ocean-abyss', name: 'Deep Ocean Blue Abyss', category: 'aesthetic', fontFamily: 'Inter', color: '#38bdf8', boxStyle: 'glass', boxBgColor: 'rgba(8, 47, 73, 0.9)', opacity: 0.95, animationType: 'liquid-ripple' },
  { id: 'crimson-velvet-royale', name: 'Crimson Velvet Royalty', category: 'hindi', fontFamily: 'Playfair Display', color: '#ffffff', boxStyle: 'pill', boxBgColor: '#881337', opacity: 1, animationType: 'shimmer' },
  { id: 'solar-flare-blaze', name: 'Solar Flare Mega Heat', category: 'animation', fontFamily: 'Anton', color: '#fef08a', boxStyle: 'box', boxBgColor: '#ea580c', opacity: 1, animationType: 'solar-pulse' },
  { id: 'frostbite-arctic-glow', name: 'Arctic Shiver Frostbite', category: 'aesthetic', fontFamily: 'Cinzel', color: '#e0f2fe', boxStyle: 'glass', boxBgColor: 'rgba(12, 74, 110, 0.85)', opacity: 0.95, animationType: 'ice-freeze' },
  { id: 'pure-contrast-whiteout', name: 'Pure Contrast Ultra Pop', category: 'viral', fontFamily: 'Archivo Black', color: '#000000', boxStyle: 'box', boxBgColor: '#ffffff', opacity: 1, animationType: 'word-pop', textTransform: 'uppercase' },
  { id: 'viral-master-retention', name: '100% Retention Hook Master', category: 'viral', fontFamily: 'Anton', color: '#fde047', boxStyle: 'box', boxBgColor: '#000000', opacity: 1, animationType: 'viral-ultimate', textTransform: 'uppercase' },
];
